### ISSUE TITLE
Excel - Roadmap Tasks

### ISSUE THREAD

**Issue by justkawal** [justkawal/excel#329]
Tasks Priority:

- [ ] Isolated Xml Structuring
- [ ] Data Correctness
- [ ] Date Validations
- [ ] Styling and Colors
- [ ] Formula Calculations
- [ ] Small Excel Size
- [ ] Tables
- [ ] Picture Addition

**Comment by justkawal** [comment]
I'm humbly sorry for all the un-attended issues in this package.
I'm trying my best to bring it upto speed with job hunt on side.
Please bear with me.

Thanks.

**Comment by taosimple** [comment]
Hope the priority of `Picture` can be elevated
